### ISSUE TITLE
Attempted to set grade failed

### ISSUE THREAD

**Issue by lunarythia** [walksanatora/PondoBot#1]
It gives me "fallback mode enabled, commands disabled"

![image](https://user-images.githubusercontent.com/63614345/143988889-2701ca57-b06e-41de-bd1c-cd8a9fc7d09a.png)

Log that the bot gave me:
```
Already up to date.

up to date, audited 79 packages in 2s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/home/pi/PondoBot/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Invalid Form Body
data.embeds[0].fields[0].value: Must be 1024 or fewer in length.
    at RequestHandler.execute (/home/pi/PondoBot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/pi/PondoBot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async CommandInteraction.reply (/home/pi/PondoBot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5) {
  method: 'post',
  path: '/interactions/915106055346855936/aW50ZXJhY3Rpb246OTE1MTA2MDU1MzQ2ODU1OTM2OkFLTFpoQ2hTOGNlUzdOcm1wMlk4Z2h0WnhSNEF2WVZKbnhqM1B5aXptVFM0anRORHRmM3lCTWhVcXNvSkwwa2ZTaWVkZlFFYlhMZXRnYUo5eVljdnZHOVphcEN1MEhXS29QV2s2ZzdkVndNVDFWT3JsN1UzWVVqbDg1bTRtVU9N/callback',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      type: 4,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,
        embeds: [
          {
            title: 'Error occured',
            type: 'rich',
            description: null,
            url: null,
            timestamp: 0,
            color: 16711680,
            fields: [Array],
            thumbnail: null,
            image: null,
            author: null,
            footer: null
          }
        ],
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: 64,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined
      }
    },
    files: []
  }
}

Node.js v17.1.0
Running in Fallback! with tag PondoBot#5845
```

**Comment by lunarythia** [comment]
**UPDATE** setting grade works now!
